# Generated by Django 5.2.12 on 2026-03-17 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiztemplate'),
        ),
        migrations.AddIndex(
            model_name='quiztemplate',
            index=models.Index(fields=['topic', 'difficulty'], name='quizzes_qui_topic_fe6254_idx'),
        ),
        migrations.AddIndex(
            model_name='quiztemplate',
            index=models.Index(fields=['status'], name='quizzes_qui_status_1660d9_idx'),
        ),
    ]
