# Generated by Django 5.2.12 on 2026-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_initial'),
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['session', 'is_correct'], name='attempts_qu_session_1c3641_idx'),
        ),
    ]
