# Generated by Django 5.2.12 on 2026-03-17 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.CharField(max_length=100)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('is_weak_topic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-mastery_score'],
            },
        ),
    ]
