# Generated by Django 5.2.12 on 2026-03-17 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmastery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['user', 'topic'], name='analytics_t_user_id_b1997e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together={('user', 'topic')},
        ),
    ]
