# Generated by Django 5.2.12 on 2026-03-17 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quiz_template_id', models.UUIDField(blank=True, null=True)),
                ('prompt_used', models.TextField()),
                ('raw_response', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('retried', 'Retried')], default='success', max_length=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
